# SPDX-FileCopyrightText: 2024 Ledger SAS
#
# SPDX-License-Identifier: Apache-2.0 OR BSD-3-Clause

[package]
name = "shield-macros"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR BSD-3-Clause"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
